name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/app.Dockerfile
          push: true
          tags: |
            morzlee/anneweb:latest
            morzlee/anneweb:${{ github.sha }}

      - name: Build and push MySQL image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/database/mysql/Dockerfile
          push: true
          tags: |
            morzlee/database:mysql-5.7-tuned
            morzlee/database:mysql-${{ github.sha }}

      - name: Build and push Redis image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/database/redis/Dockerfile
          push: true
          tags: |
            morzlee/database:redis-7.4-tuned
            morzlee/database:redis-${{ github.sha }}
